import api from "./api";
export const getItems = (p) => api.get("/items", { params: p });
export const getItem = (id) => api.get(`/items/${id}`);
export const createItem = (d) => api.post("/items", d);
export const updateItem = (id, d) => api.put(`/items/${id}`, d);
export const deleteItem = (id) => api.delete(`/items/${id}`);
export const soldItem = (id) => api.patch(`/items/${id}/sold`);
export const myListings = () => api.get("/items/my-listings");
export const adminListings = () => api.get("/admin/listings");
export const adminDelete = (id) => api.delete(`/items/${id}/admin`);
